#!/bin/bash
#The frontend is the service in RobotShop to serve the web content over Nginx.

#To Install Nginx.

yum install nginx -y &>>${LOG_FILE}
STAT_CHECK$? "nginx installation"
Download frontend
rm -rf /usr/share/nginx/html/*
STAT_CHECK$? "remove all old html pages"
## unzip /tmp/frontend.zip
## mv frontend-main/* .
## mv static/* .
## rm -rf frontend-master static README.md
## mv localhost.conf /etc/nginx/default.d/roboshop.conf
#Finally restart the service once to effect the changes.

# systemctl restart nginx